const name = document.getElementById("name")
const Class = document.getElementById("Class")
const email = document.getElementById("Email")
const StudentId = document.getElementById("StudentId")
const password = document.getElementById("Password")
let LogInBtn = document.getElementById("LogInBtn")
