const Name = document.getElementById("name")
const Class = document.getElementById("Class")
const Email = document.getElementById("Email")
const StudentId = document.getElementById("StudentId")
const Password = document.getElementById("Password")
let LogInBtn = document.getElementById("LogInBtn")
